import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import 'react-toastify/dist/ReactToastify.css';
import "@/utils/assets/css/globals.css";
import dynamic from "next/dynamic";
// import Providers from "./providers";
import BackdropCircularProgress from './../components/loading/backdrop-circular-progress';

const Providers = dynamic(() => import("./providers"), {
  ssr: false,
  loading: () => <BackdropCircularProgress />,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
